# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f866b402d4f4b7aef176521361e942428a4abd14cc2044044c6a42177744032b35deedbe060124c6141dfd8cafb50eb737ed3d3bd2cf68fcae9c69cc15d0c43

test:
  secret_key_base: 67aaf93217bec26497739f1146d025c4108d90bc3bed5347d3036069d860aa7a908ca778f29ab72ccb26acc68518a108e60c9b6ebccced9659a9431e9e6222f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
